Submission for ISSCS 2025 code a chip travel grant: MARTIn chip
sscs-ose/sscs-ose-code-a-chip.github.io pull request #113
Opened 2024-12-05 20:53 UTC by nickguimara

This submission is about a chip developed by opensource tools to test a innovative median finding algorithm and filter for particle physics experiments. This chip is currently under production by IHP.

2024-12-10 03:44 UTC, msaligane requested changes

2024-12-10 03:44 UTC, msaligane commented on main_notebook.ipynb
Please delete. This seems to be redundant.

2024-12-10 11:20 UTC, nickguimara commented on main_notebook.ipynb
Extra notebook deleted!

2024-12-11 09:01 UTC, msaligane approved these changes

2024-12-11 09:01 UTC, merged